const CONFIG = {
    introTitle: 'Chin thúi à!',
    introDesc: `Yêu Chin lắm đó. Nay sinh nhật Chin ùi,sang tuổi mới ùi,nhớ phải ngoan và học giỏi hưn nhá. Yêu tôi hơn nữa e hèm!! `,
    btnIntro: 'Ấn tiếp đi',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Yêu Be thúi lắm ý không chịu được',
    btnNo: 'Không, đồ dở hơi lew lew :)))',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh nhờ',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu Khánh lắm luôn',
    mess: 'Anh biết mà 🥰. Lớp duuuu 😘😘',
    messDesc: 'Sinh nhật vui vẻ nhá Chin',
    btnAccept: 'HiHiiii =)))))',
    }
